### ISSUE TITLE
新环境部署后push失败

### ISSUE THREAD

**Issue by fsword** [qinix/shelter#6]
可以追溯的最早的一条log如下

registry_1  | time="2016-08-14T09:27:51.083051448Z" level=error msg="response completed with error" auth.user.name=admin err.code="blob unknown" err.detail=sha256:3ffc098e1fcde191532a8b3b040a05c5896ab97048dfb95586b9e1b1bd629a9a err.message="blob unknown to registry" go.version=go1.6.1 http.request.host=192.168.90.100 http.request.id=eb89b132-1992-4895-bb33-6551754c8abf http.request.method=HEAD http.request.remoteaddr=192.168.90.100 http.request.uri="/v2/library/haproxy/blobs/sha256:3ffc098e1fcde191532a8b3b040a05c5896ab97048dfb95586b9e1b1bd629a9a" http.request.useragent="docker/1.11.2 go/go1.5.4 git-commit/b9f10c9 kernel/4.4.12-boot2docker os/linux arch/amd64 UpstreamClient(Docker-Client/1.11.0 \\(darwin\\))" http.response.contenttype="application/json; charset=utf-8" http.response.duration=4.588165ms http.response.status=404 http.response.written=157 instance.id=7ca4de83-99c0-4604-b3f6-3b32a8775e8f service=registry vars.digest="sha256:3ffc098e1fcde191532a8b3b040a05c5896ab97048dfb95586b9e1b1bd629a9a" vars.name="library/haproxy" version=v2.4.0

**Comment by fsword** [comment]
经过讨论，发现是 auth token 服务的realm设定被固化导致的

```
➜  shelter git:(master) ✗ more config/registry/config.yml 
......
auth:
  token:
    realm: http://localhost/service/token
......
```

**Comment by qinix** [comment]
Run `prepare.sh` first to fix this issue.
